apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "mongodb-service"
  DB_NAME: "prod_db"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faulty-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faulty-app
  template:
    metadata:
      labels:
        app: faulty-app
    spec:
      containers:
      - name: app
        image: node:18
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting app..."
            echo "Connecting to DB..."
            if [ -z "$DB_PASSWORD" ]; then
              echo "Auth failed: Missing DB_PASSWORD"
              exit 1
            fi
            sleep 3600
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret   # ❌ SECRET DOES NOT EXIST
              key: password


  # kubectl create secret generic db-secret \
  #   --from-literal=password=supersecure123