apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-file-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-file-app
  template:
    metadata:
      labels:
        app: missing-file-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        command: ["/bin/sh","/app/start.sh"]