
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incompatible-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: incompatible-app
  template:
    metadata:
      labels:
        app: incompatible-app
    spec:
      containers:
        - name: app
          image: python:3.10
          command: ["sh", "-c"]
          args:
            - |
              pip install flask==1.0 werkzeug==2.2.0;
              python -c "from flask import Flask; app = Flask(__name__)"